### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by displague**
Prepares the vendors and CHANGELOG for v1.1.0
and updates packngo to v0.7.0

### CODE REVIEW

**Comment by displague** [comment]
Holding off until https://github.com/packethost/packngo/pull/248 can be incorporated.
This will resolve the '404' issues seen in #25

**Comment by t0mk** [comment]
@displague looks good. I am not sure why the `TestAccMetalBGPSetup_Basic` is failing, maybe BGP disable in testing org settings?

`TestAccMetalBGPSetup_Basic` works when I run it in my org.

**Comment by displague** [comment]
@t0mk The majority of BGP errors were corrected with 0.7.0 packngo (packethost/packngo#248).  The TF 0.12 BGP error we received in this last build was an "Oh, Snap!" - not much we can do about that. The same test succeeded with TF 0.13. 
Before updating to packngo 0.7.0 all of these BGP tests were failing (since the update to 0.6.0).

Thanks for the review. This PR looks ready to go.

We'll want to follow up on the following E2E tests that failed (some new):

```
--- FAIL: TestAccMetalBGPSetup_Basic (18.14s)
    testing.go:569: Step 0 error: errors during apply:
        
        Error: Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble.
```

The following did not occur in the TF 0.12 test, so they are perhaps intermittent:

```
--- FAIL: TestAccMetalPortVlanAttachment_L2Bonded (157.79s)
    testing.go:569: Step 0 error: Check failed: Check 1/1 error: metal_device.test: Attribute 'network_type' expected "layer3", got "hybrid"
```

```
--- FAIL: TestAccMetalPortVlanAttachment_HybridMultipleVlans (956.82s)
    testing.go:569: Step 0 error: errors during apply:
        
        Error: Not found
        
          on /tmp/tf-test950481925/main.tf line 6:
          (source code not available)     
```

I don't know if we can do anything special about this one, maybe Terraform should expect statuscode = 422, message ~= /provisioning/ and retry with delays in that case:

```
--- FAIL: TestAccDataSourceMetalSpotMarketRequest_Basic (141.60s)
    testing.go:630: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: DELETE https://api.equinix.com/metal/v1/devices/a3a72995-ca31-452e-b3b4-a963c7544dd7: 422 Cannot delete a device while it is provisioning 
```
